import Classes from './aboutus.module.less';
import React from "react";
import ContentContainer from "../../components/ui/content-container/content-container";
import Head from "next/head";
import MainWrapper from "../../components/ui/wrapper/wrapper";
import { useTranslation } from "next-i18next";
import EventHeading from "../../components/eventsheadings";
import HeldEvents from '../../components/heldevents';




const AboutUs = () => {

    const { t } = useTranslation("common");
    return (
        <MainWrapper t={t}>
            <div className={Classes.container}>
                <Head>
                    <title>cumputer-club</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link
                        rel="stylesheet"
                        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
                        crossOrigin="anonymous"
                    />
                </Head>


                <ContentContainer>
                    <div className={Classes.about_us_main_container}>
                        <EventHeading label="About us" />
                        <div className={Classes.about_us_banner}>
                            <img src="/images/iustimages/image4.jpg"></img>
                        </div>

                        <div className={Classes.about_us_body}>
                            <div className={Classes.about_us_body_image}> <img src="/images/iustimages/image11.jpg" /></div>
                            <div className={Classes.about_us_description}>The Islamic University of Science and Technology (IUST), Awantipora, J&K has been established through an Act No. XVIII of 2005 dated: 7th November 2005 passed by J&K State Legislature and notified by the State Government, through Jammu & Kashmir Government Gazette dated: 11-11-2005. While the university started functioning in November, 2005 the teaching programme was started in July 2006. The Chancellor of the University is the Lieuteutant Governor of Union Territory of Jammu & Kashmir and the executive authority of the University is its Executive Council with the Vice Chancellors of University of Jammu, University of Kashmir and Baba Ghulam Shah Badshah University as members. The University is accredited by NAAC with Grade ‘B’ and is recognized by University Grants Commission (UGC) under Section 2(f) and Section 12(b) of UGC Act. The Technical and nursing programmes offered by the University are approved by All India Council for Technical Education (AICTE) and Indian Nursing Council (INC). The University has the membership of Association of Indian Universities (AIU). The University came into existence with a mandate to advance and disseminate knowledge, wisdom and understanding amongst all segments of the society within and outside the State. It is also charged with creating an environment for learning, teaching and research in the sciences, technology, humanities and social sciences and that is in keeping with the highest standards of scholarship and higher education. People belonging to all sections of society are entitled to avail the facilities and opportunities offered by the University and there is no distinction on the basis of class, caste, creed, colour or religion</div>
                        </div>

                    </div>





                </ContentContainer>
            </div>
        </MainWrapper>
    )
}
export default AboutUs;