import react from "react";
import Classes from './gallerypage.module.less';
import ContentContainer from "../../components/ui/content-container/content-container";
import MainWrapper from "../../components/ui/wrapper/wrapper";
import Head from "next/head";
import { useTranslation } from "react-i18next";
import EventsGallery from "../../components/Events-gallery";
import EventHeading from "../../components/eventsheadings";
const GalleryPage = () => {
    const { t } = useTranslation("common");
    return (

        <MainWrapper t={t}>
            <div className={Classes.container}>
                <Head>
                    <title>cumputer-club</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link
                        rel="stylesheet"
                        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
                        crossOrigin="anonymous"
                    />
                </Head>
                <ContentContainer>
                    <EventHeading label="PHOTO GALLERY " />
                    <div className={Classes.gallerypage_container}>
                        <EventsGallery />
                    </div>

                </ContentContainer>

            </div>
        </MainWrapper>

    )
}
export default GalleryPage;